#!/bin/bash
app=redirect
set -e

# Retrieve arguments
domain=$1
path=$2
is_public=$3
redirect_port=$4
redirect_path=$5

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app \
	|| (echo "Path not available: $redirect_domain$redirect_path" && exit 1)

# Add the redirection
	path=${path%/}
	sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
	sudo yunohost app setting $app domain -v "$domain"
	sudo yunohost app setting $app path -v "$path"

	# Redirect Port
		sudo yunohost app setting $app redirect_port -v "$redirect_port"
		if [ "$redirect_port" = "none" ];
		then
			sed -i "s@REDIRECT_PORT@@g" ../conf/nginx.conf
		else
			sed -i "s@REDIRECT_PORT@:$redirect_port@g" ../conf/nginx.conf
		fi

	# Redirect Path
		redirect_path=${redirect_path%/}
		sudo yunohost app setting $app redirect_path -v "$redirect_path"
		if [ "$redirect_path" = "none" ];
		then
			sed -i "s@REDIRECT_PATH@@g" ../conf/nginx.conf
		else
			sed -i "s@REDIRECT_PATH@$redirect_path@g" ../conf/nginx.conf
		fi

	# Copy nginx conf file
		sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

	# Escape uris
		sudo yunohost app setting $app is_public -v "$is_public"
		if [ "$is_public" = "Yes" ];
		then
			sudo yunohost app setting $app skipped_uris -v "/"
		fi

# Reload
sudo service nginx reload
sudo yunohost app ssowatconf